// lib/features/quran/data/surahs_data.dart
//
// Full list of 114 surahs with metadata.
// Replace ayat content in ayat_data.dart with a real Quran API when ready.

import 'package:omen/component/quran/quran_models.dart';

const List<SurahModel> kSurahs = [
  SurahModel(
      id: 1,
      name: "الفاتحة",
      ename: "Al-Fatiha",
      ayatCount: 7,
      juz: 1,
      page: 1,
      type: SurahType.makki),
  SurahModel(
      id: 2,
      name: "البقرة",
      ename: "Al-Baqara",
      ayatCount: 286,
      juz: 1,
      page: 2,
      type: SurahType.madani),
  SurahModel(
      id: 3,
      name: "آل عمران",
      ename: "Ali Imran",
      ayatCount: 200,
      juz: 3,
      page: 50,
      type: SurahType.madani),
  SurahModel(
      id: 4,
      name: "النساء",
      ename: "An-Nisa",
      ayatCount: 176,
      juz: 4,
      page: 77,
      type: SurahType.madani),
  SurahModel(
      id: 5,
      name: "المائدة",
      ename: "Al-Maida",
      ayatCount: 120,
      juz: 6,
      page: 106,
      type: SurahType.madani),
  SurahModel(
      id: 6,
      name: "الأنعام",
      ename: "Al-Anam",
      ayatCount: 165,
      juz: 7,
      page: 128,
      type: SurahType.makki),
  SurahModel(
      id: 7,
      name: "الأعراف",
      ename: "Al-Araf",
      ayatCount: 206,
      juz: 8,
      page: 151,
      type: SurahType.makki),
  SurahModel(
      id: 8,
      name: "الأنفال",
      ename: "Al-Anfal",
      ayatCount: 75,
      juz: 9,
      page: 177,
      type: SurahType.madani),
  SurahModel(
      id: 9,
      name: "التوبة",
      ename: "At-Tawba",
      ayatCount: 129,
      juz: 10,
      page: 187,
      type: SurahType.madani),
  SurahModel(
      id: 10,
      name: "يونس",
      ename: "Yunus",
      ayatCount: 109,
      juz: 11,
      page: 208,
      type: SurahType.makki),
  SurahModel(
      id: 11,
      name: "هود",
      ename: "Hud",
      ayatCount: 123,
      juz: 11,
      page: 221,
      type: SurahType.makki),
  SurahModel(
      id: 12,
      name: "يوسف",
      ename: "Yusuf",
      ayatCount: 111,
      juz: 12,
      page: 235,
      type: SurahType.makki),
  SurahModel(
      id: 13,
      name: "الرعد",
      ename: "Ar-Rad",
      ayatCount: 43,
      juz: 13,
      page: 249,
      type: SurahType.madani),
  SurahModel(
      id: 14,
      name: "إبراهيم",
      ename: "Ibrahim",
      ayatCount: 52,
      juz: 13,
      page: 255,
      type: SurahType.makki),
  SurahModel(
      id: 15,
      name: "الحجر",
      ename: "Al-Hijr",
      ayatCount: 99,
      juz: 14,
      page: 262,
      type: SurahType.makki),
  SurahModel(
      id: 16,
      name: "النحل",
      ename: "An-Nahl",
      ayatCount: 128,
      juz: 14,
      page: 267,
      type: SurahType.makki),
  SurahModel(
      id: 17,
      name: "الإسراء",
      ename: "Al-Isra",
      ayatCount: 111,
      juz: 15,
      page: 282,
      type: SurahType.makki),
  SurahModel(
      id: 18,
      name: "الكهف",
      ename: "Al-Kahf",
      ayatCount: 110,
      juz: 15,
      page: 293,
      type: SurahType.makki),
  SurahModel(
      id: 19,
      name: "مريم",
      ename: "Maryam",
      ayatCount: 98,
      juz: 16,
      page: 305,
      type: SurahType.makki),
  SurahModel(
      id: 20,
      name: "طه",
      ename: "Ta-Ha",
      ayatCount: 135,
      juz: 16,
      page: 312,
      type: SurahType.makki),
  SurahModel(
      id: 21,
      name: "الأنبياء",
      ename: "Al-Anbiya",
      ayatCount: 112,
      juz: 17,
      page: 322,
      type: SurahType.makki),
  SurahModel(
      id: 22,
      name: "الحج",
      ename: "Al-Hajj",
      ayatCount: 78,
      juz: 17,
      page: 332,
      type: SurahType.madani),
  SurahModel(
      id: 23,
      name: "المؤمنون",
      ename: "Al-Muminun",
      ayatCount: 118,
      juz: 18,
      page: 342,
      type: SurahType.makki),
  SurahModel(
      id: 24,
      name: "النور",
      ename: "An-Nur",
      ayatCount: 64,
      juz: 18,
      page: 350,
      type: SurahType.madani),
  SurahModel(
      id: 25,
      name: "الفرقان",
      ename: "Al-Furqan",
      ayatCount: 77,
      juz: 18,
      page: 359,
      type: SurahType.makki),
  SurahModel(
      id: 26,
      name: "الشعراء",
      ename: "Ash-Shuara",
      ayatCount: 227,
      juz: 19,
      page: 367,
      type: SurahType.makki),
  SurahModel(
      id: 27,
      name: "النمل",
      ename: "An-Naml",
      ayatCount: 93,
      juz: 19,
      page: 377,
      type: SurahType.makki),
  SurahModel(
      id: 28,
      name: "القصص",
      ename: "Al-Qasas",
      ayatCount: 88,
      juz: 20,
      page: 385,
      type: SurahType.makki),
  SurahModel(
      id: 29,
      name: "العنكبوت",
      ename: "Al-Ankabut",
      ayatCount: 69,
      juz: 20,
      page: 396,
      type: SurahType.makki),
  SurahModel(
      id: 30,
      name: "الروم",
      ename: "Ar-Rum",
      ayatCount: 60,
      juz: 21,
      page: 404,
      type: SurahType.makki),
  SurahModel(
      id: 31,
      name: "لقمان",
      ename: "Luqman",
      ayatCount: 34,
      juz: 21,
      page: 411,
      type: SurahType.makki),
  SurahModel(
      id: 32,
      name: "السجدة",
      ename: "As-Sajda",
      ayatCount: 30,
      juz: 21,
      page: 415,
      type: SurahType.makki),
  SurahModel(
      id: 33,
      name: "الأحزاب",
      ename: "Al-Ahzab",
      ayatCount: 73,
      juz: 21,
      page: 418,
      type: SurahType.madani),
  SurahModel(
      id: 34,
      name: "سبأ",
      ename: "Saba",
      ayatCount: 54,
      juz: 22,
      page: 428,
      type: SurahType.makki),
  SurahModel(
      id: 35,
      name: "فاطر",
      ename: "Fatir",
      ayatCount: 45,
      juz: 22,
      page: 434,
      type: SurahType.makki),
  SurahModel(
      id: 36,
      name: "يس",
      ename: "Ya-Sin",
      ayatCount: 83,
      juz: 22,
      page: 440,
      type: SurahType.makki),
  SurahModel(
      id: 37,
      name: "الصافات",
      ename: "As-Saffat",
      ayatCount: 182,
      juz: 23,
      page: 446,
      type: SurahType.makki),
  SurahModel(
      id: 38,
      name: "ص",
      ename: "Sad",
      ayatCount: 88,
      juz: 23,
      page: 453,
      type: SurahType.makki),
  SurahModel(
      id: 39,
      name: "الزمر",
      ename: "Az-Zumar",
      ayatCount: 75,
      juz: 23,
      page: 458,
      type: SurahType.makki),
  SurahModel(
      id: 40,
      name: "غافر",
      ename: "Ghafir",
      ayatCount: 85,
      juz: 24,
      page: 467,
      type: SurahType.makki),
  SurahModel(
      id: 41,
      name: "فصلت",
      ename: "Fussilat",
      ayatCount: 54,
      juz: 24,
      page: 477,
      type: SurahType.makki),
  SurahModel(
      id: 42,
      name: "الشورى",
      ename: "Ash-Shura",
      ayatCount: 53,
      juz: 25,
      page: 483,
      type: SurahType.makki),
  SurahModel(
      id: 43,
      name: "الزخرف",
      ename: "Az-Zukhruf",
      ayatCount: 89,
      juz: 25,
      page: 489,
      type: SurahType.makki),
  SurahModel(
      id: 44,
      name: "الدخان",
      ename: "Ad-Dukhan",
      ayatCount: 59,
      juz: 25,
      page: 496,
      type: SurahType.makki),
  SurahModel(
      id: 45,
      name: "الجاثية",
      ename: "Al-Jathiya",
      ayatCount: 37,
      juz: 25,
      page: 499,
      type: SurahType.makki),
  SurahModel(
      id: 46,
      name: "الأحقاف",
      ename: "Al-Ahqaf",
      ayatCount: 35,
      juz: 26,
      page: 502,
      type: SurahType.makki),
  SurahModel(
      id: 47,
      name: "محمد",
      ename: "Muhammad",
      ayatCount: 38,
      juz: 26,
      page: 507,
      type: SurahType.madani),
  SurahModel(
      id: 48,
      name: "الفتح",
      ename: "Al-Fath",
      ayatCount: 29,
      juz: 26,
      page: 511,
      type: SurahType.madani),
  SurahModel(
      id: 49,
      name: "الحجرات",
      ename: "Al-Hujurat",
      ayatCount: 18,
      juz: 26,
      page: 515,
      type: SurahType.madani),
  SurahModel(
      id: 50,
      name: "ق",
      ename: "Qaf",
      ayatCount: 45,
      juz: 26,
      page: 518,
      type: SurahType.makki),
  SurahModel(
      id: 51,
      name: "الذاريات",
      ename: "Adh-Dhariyat",
      ayatCount: 60,
      juz: 26,
      page: 520,
      type: SurahType.makki),
  SurahModel(
      id: 52,
      name: "الطور",
      ename: "At-Tur",
      ayatCount: 49,
      juz: 27,
      page: 523,
      type: SurahType.makki),
  SurahModel(
      id: 53,
      name: "النجم",
      ename: "An-Najm",
      ayatCount: 62,
      juz: 27,
      page: 526,
      type: SurahType.makki),
  SurahModel(
      id: 54,
      name: "القمر",
      ename: "Al-Qamar",
      ayatCount: 55,
      juz: 27,
      page: 528,
      type: SurahType.makki),
  SurahModel(
      id: 55,
      name: "الرحمن",
      ename: "Ar-Rahman",
      ayatCount: 78,
      juz: 27,
      page: 531,
      type: SurahType.madani),
  SurahModel(
      id: 56,
      name: "الواقعة",
      ename: "Al-Waqia",
      ayatCount: 96,
      juz: 27,
      page: 534,
      type: SurahType.makki),
  SurahModel(
      id: 57,
      name: "الحديد",
      ename: "Al-Hadid",
      ayatCount: 29,
      juz: 27,
      page: 537,
      type: SurahType.madani),
  SurahModel(
      id: 58,
      name: "المجادلة",
      ename: "Al-Mujadila",
      ayatCount: 22,
      juz: 28,
      page: 542,
      type: SurahType.madani),
  SurahModel(
      id: 59,
      name: "الحشر",
      ename: "Al-Hashr",
      ayatCount: 24,
      juz: 28,
      page: 545,
      type: SurahType.madani),
  SurahModel(
      id: 60,
      name: "الممتحنة",
      ename: "Al-Mumtahana",
      ayatCount: 13,
      juz: 28,
      page: 549,
      type: SurahType.madani),
  SurahModel(
      id: 61,
      name: "الصف",
      ename: "As-Saf",
      ayatCount: 14,
      juz: 28,
      page: 551,
      type: SurahType.madani),
  SurahModel(
      id: 62,
      name: "الجمعة",
      ename: "Al-Jumua",
      ayatCount: 11,
      juz: 28,
      page: 553,
      type: SurahType.madani),
  SurahModel(
      id: 63,
      name: "المنافقون",
      ename: "Al-Munafiqun",
      ayatCount: 11,
      juz: 28,
      page: 554,
      type: SurahType.madani),
  SurahModel(
      id: 64,
      name: "التغابن",
      ename: "At-Taghabun",
      ayatCount: 18,
      juz: 28,
      page: 556,
      type: SurahType.madani),
  SurahModel(
      id: 65,
      name: "الطلاق",
      ename: "At-Talaq",
      ayatCount: 12,
      juz: 28,
      page: 558,
      type: SurahType.madani),
  SurahModel(
      id: 66,
      name: "التحريم",
      ename: "At-Tahrim",
      ayatCount: 12,
      juz: 28,
      page: 560,
      type: SurahType.madani),
  SurahModel(
      id: 67,
      name: "الملك",
      ename: "Al-Mulk",
      ayatCount: 30,
      juz: 29,
      page: 562,
      type: SurahType.makki),
  SurahModel(
      id: 68,
      name: "القلم",
      ename: "Al-Qalam",
      ayatCount: 52,
      juz: 29,
      page: 564,
      type: SurahType.makki),
  SurahModel(
      id: 69,
      name: "الحاقة",
      ename: "Al-Haqqa",
      ayatCount: 52,
      juz: 29,
      page: 566,
      type: SurahType.makki),
  SurahModel(
      id: 70,
      name: "المعارج",
      ename: "Al-Maarij",
      ayatCount: 44,
      juz: 29,
      page: 568,
      type: SurahType.makki),
  SurahModel(
      id: 71,
      name: "نوح",
      ename: "Nuh",
      ayatCount: 28,
      juz: 29,
      page: 570,
      type: SurahType.makki),
  SurahModel(
      id: 72,
      name: "الجن",
      ename: "Al-Jinn",
      ayatCount: 28,
      juz: 29,
      page: 572,
      type: SurahType.makki),
  SurahModel(
      id: 73,
      name: "المزمل",
      ename: "Al-Muzzammil",
      ayatCount: 20,
      juz: 29,
      page: 574,
      type: SurahType.makki),
  SurahModel(
      id: 74,
      name: "المدثر",
      ename: "Al-Muddathir",
      ayatCount: 56,
      juz: 29,
      page: 575,
      type: SurahType.makki),
  SurahModel(
      id: 75,
      name: "القيامة",
      ename: "Al-Qiyama",
      ayatCount: 40,
      juz: 29,
      page: 577,
      type: SurahType.makki),
  SurahModel(
      id: 76,
      name: "الإنسان",
      ename: "Al-Insan",
      ayatCount: 31,
      juz: 29,
      page: 578,
      type: SurahType.madani),
  SurahModel(
      id: 77,
      name: "المرسلات",
      ename: "Al-Mursalat",
      ayatCount: 50,
      juz: 29,
      page: 580,
      type: SurahType.makki),
  SurahModel(
      id: 78,
      name: "النبأ",
      ename: "An-Naba",
      ayatCount: 40,
      juz: 30,
      page: 582,
      type: SurahType.makki),
  SurahModel(
      id: 79,
      name: "النازعات",
      ename: "An-Naziat",
      ayatCount: 46,
      juz: 30,
      page: 583,
      type: SurahType.makki),
  SurahModel(
      id: 80,
      name: "عبس",
      ename: "Abasa",
      ayatCount: 42,
      juz: 30,
      page: 585,
      type: SurahType.makki),
  SurahModel(
      id: 81,
      name: "التكوير",
      ename: "At-Takwir",
      ayatCount: 29,
      juz: 30,
      page: 586,
      type: SurahType.makki),
  SurahModel(
      id: 82,
      name: "الانفطار",
      ename: "Al-Infitar",
      ayatCount: 19,
      juz: 30,
      page: 587,
      type: SurahType.makki),
  SurahModel(
      id: 83,
      name: "المطففين",
      ename: "Al-Mutaffifin",
      ayatCount: 36,
      juz: 30,
      page: 587,
      type: SurahType.makki),
  SurahModel(
      id: 84,
      name: "الانشقاق",
      ename: "Al-Inshiqaq",
      ayatCount: 25,
      juz: 30,
      page: 589,
      type: SurahType.makki),
  SurahModel(
      id: 85,
      name: "البروج",
      ename: "Al-Buruj",
      ayatCount: 22,
      juz: 30,
      page: 590,
      type: SurahType.makki),
  SurahModel(
      id: 86,
      name: "الطارق",
      ename: "At-Tariq",
      ayatCount: 17,
      juz: 30,
      page: 591,
      type: SurahType.makki),
  SurahModel(
      id: 87,
      name: "الأعلى",
      ename: "Al-Ala",
      ayatCount: 19,
      juz: 30,
      page: 591,
      type: SurahType.makki),
  SurahModel(
      id: 88,
      name: "الغاشية",
      ename: "Al-Ghashiya",
      ayatCount: 26,
      juz: 30,
      page: 592,
      type: SurahType.makki),
  SurahModel(
      id: 89,
      name: "الفجر",
      ename: "Al-Fajr",
      ayatCount: 30,
      juz: 30,
      page: 593,
      type: SurahType.makki),
  SurahModel(
      id: 90,
      name: "البلد",
      ename: "Al-Balad",
      ayatCount: 20,
      juz: 30,
      page: 594,
      type: SurahType.makki),
  SurahModel(
      id: 91,
      name: "الشمس",
      ename: "Ash-Shams",
      ayatCount: 15,
      juz: 30,
      page: 595,
      type: SurahType.makki),
  SurahModel(
      id: 92,
      name: "الليل",
      ename: "Al-Layl",
      ayatCount: 21,
      juz: 30,
      page: 595,
      type: SurahType.makki),
  SurahModel(
      id: 93,
      name: "الضحى",
      ename: "Ad-Duha",
      ayatCount: 11,
      juz: 30,
      page: 596,
      type: SurahType.makki),
  SurahModel(
      id: 94,
      name: "الشرح",
      ename: "Ash-Sharh",
      ayatCount: 8,
      juz: 30,
      page: 596,
      type: SurahType.makki),
  SurahModel(
      id: 95,
      name: "التين",
      ename: "At-Tin",
      ayatCount: 8,
      juz: 30,
      page: 597,
      type: SurahType.makki),
  SurahModel(
      id: 96,
      name: "العلق",
      ename: "Al-Alaq",
      ayatCount: 19,
      juz: 30,
      page: 597,
      type: SurahType.makki),
  SurahModel(
      id: 97,
      name: "القدر",
      ename: "Al-Qadr",
      ayatCount: 5,
      juz: 30,
      page: 598,
      type: SurahType.makki),
  SurahModel(
      id: 98,
      name: "البينة",
      ename: "Al-Bayyina",
      ayatCount: 8,
      juz: 30,
      page: 598,
      type: SurahType.madani),
  SurahModel(
      id: 99,
      name: "الزلزلة",
      ename: "Az-Zalzala",
      ayatCount: 8,
      juz: 30,
      page: 599,
      type: SurahType.madani),
  SurahModel(
      id: 100,
      name: "العاديات",
      ename: "Al-Adiyat",
      ayatCount: 11,
      juz: 30,
      page: 599,
      type: SurahType.makki),
  SurahModel(
      id: 101,
      name: "القارعة",
      ename: "Al-Qaria",
      ayatCount: 11,
      juz: 30,
      page: 600,
      type: SurahType.makki),
  SurahModel(
      id: 102,
      name: "التكاثر",
      ename: "At-Takathur",
      ayatCount: 8,
      juz: 30,
      page: 600,
      type: SurahType.makki),
  SurahModel(
      id: 103,
      name: "العصر",
      ename: "Al-Asr",
      ayatCount: 3,
      juz: 30,
      page: 601,
      type: SurahType.makki),
  SurahModel(
      id: 104,
      name: "الهمزة",
      ename: "Al-Humaza",
      ayatCount: 9,
      juz: 30,
      page: 601,
      type: SurahType.makki),
  SurahModel(
      id: 105,
      name: "الفيل",
      ename: "Al-Fil",
      ayatCount: 5,
      juz: 30,
      page: 601,
      type: SurahType.makki),
  SurahModel(
      id: 106,
      name: "قريش",
      ename: "Quraysh",
      ayatCount: 4,
      juz: 30,
      page: 602,
      type: SurahType.makki),
  SurahModel(
      id: 107,
      name: "الماعون",
      ename: "Al-Maun",
      ayatCount: 7,
      juz: 30,
      page: 602,
      type: SurahType.makki),
  SurahModel(
      id: 108,
      name: "الكوثر",
      ename: "Al-Kawthar",
      ayatCount: 3,
      juz: 30,
      page: 602,
      type: SurahType.makki),
  SurahModel(
      id: 109,
      name: "الكافرون",
      ename: "Al-Kafirun",
      ayatCount: 6,
      juz: 30,
      page: 603,
      type: SurahType.makki),
  SurahModel(
      id: 110,
      name: "النصر",
      ename: "An-Nasr",
      ayatCount: 3,
      juz: 30,
      page: 603,
      type: SurahType.madani),
  SurahModel(
      id: 111,
      name: "المسد",
      ename: "Al-Masad",
      ayatCount: 5,
      juz: 30,
      page: 603,
      type: SurahType.makki),
  SurahModel(
      id: 112,
      name: "الإخلاص",
      ename: "Al-Ikhlas",
      ayatCount: 4,
      juz: 30,
      page: 604,
      type: SurahType.makki),
  SurahModel(
      id: 113,
      name: "الفلق",
      ename: "Al-Falaq",
      ayatCount: 5,
      juz: 30,
      page: 604,
      type: SurahType.makki),
  SurahModel(
      id: 114,
      name: "الناس",
      ename: "An-Nas",
      ayatCount: 6,
      juz: 30,
      page: 604,
      type: SurahType.makki),
];
